version: '3.4'
services:
  bento-dataloader:
    container_name: dataloader
    build:
      context: .
      dockerfile: ./dataloader/Dockerfile
      args:
        BENTO_DATA_MODEL: ${BENTO_DATA_MODEL}
        NEO4J_USER: ${NEO4J_USER}
        NEO4J_PASS: ${NEO4J_PASS}
        NEO4J_HOST: ${NEO4J_HOST}
    networks:
      - default