version: '3.4'
services:
  bento-backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/backend
      args:
        FRONTEND_SOURCE_FOLDER: ${FRONTEND_SOURCE_FOLDER}
        BACKEND_SOURCE_FOLDER: ${BACKEND_SOURCE_FOLDER}
        NEO4J_USER: ${NEO4J_USER}
        NEO4J_PASS: ${NEO4J_PASS}
    environment:
      - NEO4J_URL=bolt://${NEO4J_HOST}:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASS}
      #- NEO4J_GRAPHQL_ENDPOINT=http://${NEO4J_HOST}:7474/graphql/
      - BENTO_API_VERSION=${BACKEND_BRANCH}
      - AUTH_ENDPOINT=http://${BACKEND_HOST}/api/auth
      - REDIS_ENABLE=false
      - REDIS_USE_CLUSTER=false
      - REDIS_HOST=""
      - REDIS_FILTER_ENABLE=false
      - ES_HOST=${ES_HOST}
      #- ES_FILTER_ENABLED=true
      - GRAPHQL_SCHEMA=graphql/bento-extended.graphql
      - GRAPHQL_ES_SCHEMA=graphql/bento-private-es-schema.graphql
      - GRAPHQL_PUBLIC_SCHEMA=graphql/bento-extended.graphql
      - GRAPHQL_PUBLIC_ES_SCHEMA=graphql/bento-public-es-schema.graphql
    networks:
      - default
    ports:
      - 8080:8080
    restart: always

  bento-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/frontend
      args:
        FRONTEND_SOURCE_FOLDER: ${FRONTEND_SOURCE_FOLDER}
        BACKEND_SOURCE_FOLDER: ${BACKEND_SOURCE_FOLDER}
        BENTO_DATA_MODEL: ${BENTO_DATA_MODEL}
        NEO4J_USER: ${NEO4J_USER}
        NEO4J_PASS: ${NEO4J_PASS}
        NEO4J_HOST: ${NEO4J_HOST}
        ES_HOST: ${ES_HOST}
    environment:
      - REACT_APP_BACKEND_API=http://${BACKEND_HOST}:8080/v1/graphql/
      - REACT_APP_BACKEND_PUBLIC_API=http://${BACKEND_HOST}:8080/v1/public-graphql/
      - REACT_APP_FILE_SERVICE_API=http://${FILES_HOST}:8081/api/files/
      - REACT_APP_ABOUT_CONTENT_URL=https://raw.githubusercontent.com/CBIIT/bento-frontend/master/src/content/dev/aboutPagesContent.yaml
      - REACT_APP_BE_VERSION=${BACKEND_BRANCH}
      - REACT_APP_FE_VERSION=${FRONTEND_BRANCH}
      - REACT_APP_AUTH_API=http://localhost:8085
      - REACT_APP_AUTH_SERVICE_API=http://localhost/api/auth
      - REACT_APP_USER_SERVICE_API=http://localhost/api/users
      - REACT_APP_NIH_CLIENT_ID=
      - REACT_APP_NIH_AUTH_URL=- REACT_APP_GOOGLE_CLIENT_ID
      - REACT_APP_GOOGLE_CLIENT_ID=${AUTH_IDP_CLIENT_ID}
    volumes:
      - ./${FRONTEND_SOURCE_FOLDER}:/usr/local/bento-frontend
      - /usr/local/bento-frontend/node_modules
    depends_on:
      - neo4j
      - bento-backend
      - bento-files
      - bento-es
    networks:
      - default
    ports:
      - 80:80
      - 8085:3000
    restart: always

  bento-files:
    container_name: files
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/filedownload
      args:
        FILES_BRANCH: ${FILES_BRANCH}
    environment:
      - VERSION=${FILES_BRANCH}
      - DATE=${DATE}
      - PROJECT=BENTO
      - URL_SRC=DUMMY
      - BACKEND_URL=http://${BACKEND_HOST}:8080/v1/graphql/
    networks:
      - default
    ports:
      - 8081:8081
    restart: always

#  bento-auth:
#    container_name: auth
#    build:
#      context: .
#      dockerfile: ./dockerfiles/${BUILD_MODE}/auth
#      args:
#        AUTH_BRANCH: ${AUTH_BRANCH}
#    environment:
#      - VERSION=${AUTH_BRANCH}
#      - DATE=${DATE}
#      - PROJECT=BENTO
#      - COOKIE_SECRET=${AUTH_COOKIE_SECRET}
#      - IDP=google
#      - CLIENT_ID=${AUTH_IDP_CLIENT_ID}
#      - CLIENT_SECRET=${AUTH_IDP_CLIENT_SECRET}
#      - REDIRECT_URL=http://localhost:8085
#    networks:
#      - default
#    ports:
#      - 8082:8082
#    restart: always

  bento-es:
    container_name: bento-es
    image: elasticsearch:7.10.1
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - network.bind_host=0.0.0.0
      - network.host=0.0.0.0
      - discovery.type=single-node
    depends_on:
      - neo4j
    networks:
      - default
    ports:
      - 8086:80
      - 9200:9200
      - 9300:9300

  neo4j:
    container_name: neo4j
    build:
      context: .
      dockerfile: ./dockerfiles/${BUILD_MODE}/neo4j
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      - NEO4J_PASS=${NEO4J_PASS}
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - default
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:
  neo4j-logs: